dist: xenial

language: node_js

node_js:
  - "10"

stages:
  - lint
  - deploy

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      script: make && make docker/run target=lint
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/terraform-external-file-cache
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [TERRAFORM-EXTERNAL-FILE-CACHE v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/terraform-external-file-cache/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: C8Mo8pyW/pA50TXGM+49xyZtlkjsGsifZDYt8Hn+2sU4WsciuXgfFisuTDnCGnW2JNvqmWSh2QUzZ2X+f8sarO/cDtBTQ9AwDU+8WwQM4zzdVJekDZsnO29yvs3FPTTHOUb/DfaB0kBi572bgbzA8zQOwHtLzhNAh6lkgMQ+SiGxQRqjUkvcX69Hgx+zDooudfhkTk28Fs4twgz8yaN7WGb9vELUn5353uuJShbzjW0vHMAQXJEIOPgkmOW4was5jAV96vCazn/lVBPPzCwvHMFeqw5v9KHwnsLUrLbJSgoJGxy1zwevvH2zbkvXAcrvON/6CUzoido29pFV0GG/cglmWwVB6d9kHgGQxeZcr6qPyoWnbt2rJBnxXnyupVNa8g1TPV+6gdkSdnUZ1G9taG+Q2d33Jo2ba+2+AB36cb8OBnjEIESjc5/X5ejKP2Eb16oAucUvz1IUH0wKePMJ6qToFLJlEOO0u9akd2IAIk9xxMI9WFB5gDrV5i0P5T9lQuhcdR4tjwzzFPt0voEcEkDVSuCj0PK5N0AJujkwlSiNxJ5I6T56/avJ2fK/ralt7opDqTgdxZ2xMOubU8bOLYfG/LhRAmMHNpLJqRhQa5nRe4MIEHIaVADd21kU7UdQW8pQhWKhZhdNkPy0CR+zBwSnPDUgMTn7Wurg87+tnS4=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/terraform-external-file-cache
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
